on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - uses: actions/checkout@v2

      - run: go get -v -t -d ./...

      - run: go build -v .
